project:
  type: website
  output-dir: docs
  
website:
  title: "Transformer model"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: transfer.qmd
      - href: practice.qmd
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Loc cao"

format:
  html:
    theme: 
      light: theme-light.scss
      dark: theme-dark.scss
    toc: true

editor: source

